#  EVENT_TYPE
EV_SYN = 0
EV_KEY = 1
EV_REL = 2
EV_ABS = 3

# OP
SYN_REPORT = 0
SYN_MT_REPORT = 2
ABS_MT_SLOT = 47
ABS_MT_TOUCH_MAJOR = 48
ABS_MT_WIDTH_MAJOR = 50
ABS_MT_POSITION_X = 53
ABS_MT_POSITION_Y = 54
ABS_MT_TRACKING_ID = 57
ABS_MT_PRESSURE = 58
BTN_TOUCH = 330

# COMMAND
RECORD_EVENT_NEW = 1
RECORD_EVENT_CONTINUE = 2
REPLAY_EVENT = 3
SHOW_EVENT = 4
HANDLE_EVENT_INPUT = 5
REPLAY_EVENT_INPUT = 6
SHOW_EVENT_INPUT = 7
HANDLE_MINITOUCH = 8
SHOW_MINITOUCH = 9
REPLAY_MINITOUCH = 10

# ACTION
KEY_NONE = 0
KEY_DOWN = 1
KEY_UP = 2
